# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tagged Release

on:
  push:
    tags: [ "v*" ]

jobs:
  create-nuget-package:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x.x
      - name: Pack NuGet Package
        run: dotnet pack FsdConnectorNet/FsdConnectorNet.csproj -o ${{ github.workspace }}/out/nuget --include-symbols
      - name: Push NuGet Package
        shell: pwsh
        run: |
          cd ${{ github.workspace }}/out/nuget
          dotnet nuget push *.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}